---
- hosts: guests:extras
#- hosts: extras
  gather_facts: no
  become: yes
  tasks:
    - group: name=wheel
    - user: name=micug groups=wheel shell=/bin/bash
    - copy: src=../files/etc/profile.d/bashrc dest=/home/micug/.profile owner=micug mode=755

- hosts: guests:extras
#- hosts: extras
  gather_facts: no
  become: yes
  become_user: micug
  tasks:
    - name: Set authorized keys taken from url
      ansible.posix.authorized_key:
        user: micug
        state: present
        key: https://github.com/GITHUB_USER_NAME.keys # if you change your GitHub account name, you can use this command (ssh micug@xx.xx.xx.xx)
