---
- hosts: guests:extras
#- hosts: extras
  gather_facts: no
  become: yes
  tasks:
    - user: name=micug groups=wheel shell=/bin/bash
    - copy: src=../files/etc/profile.d/bashrc dest=/home/micug/.profile owner=micug mode=755
